CREATE TABLE IF NOT EXISTS submissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_name TEXT NOT NULL,
  parent_phone TEXT,
  parent_email TEXT,
  child_name TEXT NOT NULL,
  child_age INTEGER,
  notes TEXT,
  active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS availability (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  submission_id BIGINT NOT NULL,
  day TEXT NOT NULL,
  time_slot TEXT NOT NULL,
  FOREIGN KEY (submission_id) REFERENCES submissions(id) ON DELETE CASCADE
);

-- Enable Row Level Security (RLS) and grant Anonymous API access to both tables
ALTER TABLE submissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE availability ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist (to ensure fresh clean policy setup without erroring)
DROP POLICY IF EXISTS "Enable all access for anon users" ON submissions;
DROP POLICY IF EXISTS "Enable all access for anon users" ON availability;

CREATE POLICY "Enable all access for anon users" 
  ON submissions 
  FOR ALL 
  TO anon 
  USING (true) 
  WITH CHECK (true);

CREATE POLICY "Enable all access for anon users" 
  ON availability 
  FOR ALL 
  TO anon 
  USING (true) 
  WITH CHECK (true);
